name: 'Home Assistant helper: VCN'
description: 'GitHub action helper: VCN'
inputs:
  vcn_version:
    description: Codenotary VCN version
    required: false
    default: "v0.9.8"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        mkdir -p "${{ github.action_path }}/bin"
        curl -Lo "${{ github.action_path }}/bin/vcn" https://github.com/codenotary/vcn/releases/download/${{ inputs.vcn_version }}/vcn-${{ inputs.vcn_version }}-linux-amd64-static
        chmod a+x "${{ github.action_path }}/bin/vcn"
        echo "${{ github.action_path }}/bin" >> "$GITHUB_PATH"
