name: 'Home Assistant helper: CodeNotary'
description: 'GitHub action helper: CodeNotary'
inputs:
  user:
    description: Username for CodeNotary login
    required: true
  password:
    description: Password for CodeNotary login
    required: true
  signer:
    description: Organisation or signerID for CodeNotary signing
    required: true
  source:
    description: Source for CodeNotary signing
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: bash <(curl https://getvcn.codenotary.com -L)

    - shell: bash
      run: |
        if [[ "$VCN_SIGNER" =~ ^0x ]]; then
          local vcn_cli=("--signerID")
        else
          local vcn_cli=("--org")
        fi

        state="$(vcn authenticate "$vcn_cli" "$VCN_SIGNER" --output json ${{ inputs.source }} | jq '.verification.status // 2')"
        if [[ "${state}" == "2" ]]; then
          vcn login
          vcn notarize --public ${{ inputs.source }}
        else
          echo "Target is already verified."
        fi
      env:
        VCN_SIGNER: ${{ inputs.signer }}
        VCN_OTP_EMPTY: true
        VCN_USER: ${{ inputs.user }}
        VCN_PASSWORD: ${{ inputs.password }}
        VCN_NOTARIZATION_PASSWORD: ${{ inputs.password }}
