name: 'Home Assistant helper: Codenotary'
description: 'GitHub action helper: Codenotary'
inputs:
  source:
    description: Source for Codenotary signing
    required: true
  version:
    description: Codenotary CAS version
    required: false
    default: "v1.0.2"
  token:
    description: Codenotary CAS API token
    required: true
  signer:
    description: CAS Signer ID/Email
    required: false
    default: "notary@home-assistant.io"
  asset:
    description: CAS Asset name
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: home-assistant/actions/helpers/cas@master
      with:
        version: ${{ inputs.version }}

    - shell: bash
      name: Codenotary Open Source Attestation Service
      env:
        INPUTS_ASSET: ${{ inputs.asset }}
        INPUTS_SOURCE: ${{ inputs.source }}
        INPUTS_SIGNER: ${{ inputs.signer }}
        INPUTS_TOKEN: ${{ inputs.token }}
      run: |
        cas_cli=()
        if [[ -n "$INPUTS_ASSET" ]]; then
          cas_cli+=("--name" "$INPUTS_ASSET")
        fi
        
        input_source=()
        if [[ "$INPUTS_SOURCE" =~ ^hash ]]; then
          raw_input="$INPUTS_SOURCE"
          input_source+=("--hash" "${raw_input#*//}")
        else
          input_source+=("$INPUTS_SOURCE")
        fi

        if ! cas authenticate --silent --signerID "$INPUTS_SIGNER" "${input_source[@]}"; then
          CAS_API_KEY="$INPUTS_TOKEN" cas login
          CAS_API_KEY="$INPUTS_TOKEN" cas notarize --ci-attr "${cas_cli[@]}" "${input_source[@]}"
        else
          echo "Target is already verified."
        fi
