name: 'Home Assistant helper: CodeNotary'
description: 'GitHub action helper: CodeNotary'
inputs:
  user:
    description: Username for CodeNotary login
    required: true
  password:
    description: Password for CodeNotary login
    required: true
  organisation:
    description: Organisation for CodeNotary signing
    required: true
  source:
    description: Source for CodeNotary signing
    required: true
  vcn_version:
    description: CodeNotary VCN version
    required: false
    default: "v0.9.8"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        mkdir -p "${{ github.action_path }}/bin"
        curl -Lo "${{ github.action_path }}/bin/vcn" https://github.com/vchain-us/vcn/releases/download/${{ inputs.vcn_version }}/vcn-${{ inputs.vcn_version }}-linux-amd64-static
        chmod a+x "${{ github.action_path }}/bin/vcn"
        echo "${{ github.action_path }}/bin" >> "$GITHUB_PATH"

    - shell: bash
      run: |
        if ! vcn authenticate --silent ${{ inputs.source }}; then
          vcn login
          vcn notarize --public ${{ inputs.source }}
        else
          echo "Target is already verified."
        fi
      env:
        VCN_ORG: ${{ inputs.organisation }}
        VCN_OTP_EMPTY: true
        VCN_USER: ${{ inputs.user }}
        VCN_PASSWORD: ${{ inputs.password }}
        VCN_NOTARIZATION_PASSWORD: ${{ inputs.password }}
