name: 'Home Assistant helper: version'
description: 'GitHub action helper: version'
inputs:
  type:
    description: The type of target to check against (core, supervisor, plugin, generic)
    required: false
    default: 'generic'
outputs:
  version:
    description: The version found for the requested type
    value: ${{ steps.version.outputs.version }}
  stable:
    description: Returns "true" if it is a stable build, else "false"
    value: ${{ steps.version.outputs.stable }}
  channel:
    description: Returns suggested channel.
    value: ${{ steps.channel.outputs.channel }}
  publish:
    description: Returns "true" if it should be published, else "false"
    value: ${{ steps.publish.outputs.publish }}
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if [[ -z "${{ inputs.type }}" ]];then
          echo "::error::Missing required key 'type' input!"
          exit 1
        fi

    - shell: bash
      id: version
      run: |
        version=$(echo "${{ github.ref }}" | awk -F"/" '{print $NF}' )

        if [[ ! -z "${{ github.event.inputs.version }}" ]]; then
          version="${{ github.event.inputs.version }}"

        elif [[ "${version}" =~ (master|main) && "${{ inputs.type }}" =~ (supervisor|plugin|generic) ]]; then
          today="$(date --utc '+%Y-%m-%d')"
          midnight_timestamp="$(date --utc +%s --date=$today)"
          calver_date="$(date --utc --date=$today '+%Y.%m.dev%d')"
          commit_count="$(git rev-list --count --since=$midnight_timestamp HEAD)"
          commit_count="$(printf "%02d" ${commit_count})"
          version="${calver_date}${commit_count}"

        elif [[ "${version}" == "merge" && "${{ inputs.type }}" =~ (supervisor|plugin|generic) ]]; then
          version="${{ github.sha }}"

        elif [[ "${version}" == "dev" && "${{ inputs.type }}" == "core" ]]; then
          python3 -m pip install packaging
          python3 -m pip install .
          python3 script/version_bump.py nightly
          version="$(python3 ${{ github.action_path }}/../read_version_cfg.py setup.cfg)"
        fi

        if [[ ! -z "${{ github.event.inputs.stable }}" ]]; then
          stable="${{ github.event.inputs.stable }}"
        elif [[ "${{ github.event_name }}" == "release" ]]; then
          stable="true"
        else
          stable="false"
        fi

        echo "::set-output name=stable::$stable"
        echo "::set-output name=version::$version"

    - shell: bash
      run: |
        if [[ "${{ inputs.type }}" == "supervisor" ]]; then
          sed -i "s/SUPERVISOR_VERSION .*/SUPERVISOR_VERSION = \"${{ steps.version.outputs.version }}\"/g" supervisor/const.py
        fi

    - shell: bash
      id: channel
      run: |
        if [[ ! -z "${{ github.event.inputs.channel }}" ]]; then
          echo "::set-output name=channel::${{ github.event.inputs.channel }}"

        elif [[ "${{ inputs.type }}" =~ (plugin|supervisor) ]]; then
          if [[ "${{ steps.version.outputs.stable }}" == "true" ]]; then
            echo "::set-output name=channel::beta"
          else
            echo "::set-output name=channel::dev"
          fi

        elif [[ "${{ inputs.type }}" == "core" ]]; then
          if [[ "${{ steps.version.outputs.version }}" =~ dev ]]; then
            echo "::set-output name=channel::dev"
          elif [[ "${{ steps.version.outputs.version }}" =~ b ]]; then
            echo "::set-output name=channel::beta"
          else
            echo "::set-output name=channel::stable"
          fi
        fi

    - shell: bash
      id: publish
      run: |
        if [[ ! -z "${{ github.event.inputs.publish }}" ]]; then
            echo "::set-output name=publish::${{ github.event.inputs.publish }}"

        elif [[ "${{ inputs.type }}" =~ (plugin|supervisor) ]]; then
          if [[ ! -z "${{ github.head_ref }}" ]]; then
            echo "::set-output name=publish::false"
          elif [[ "${{ github.event_name }}" =~ (release|push) ]]; then
            echo "::set-output name=publish::true"
          else
            echo "::set-output name=publish::false"
          fi

        elif [[ "${{ inputs.type }}" == "core" ]]; then
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "::set-output name=publish::true"
          else
            echo "::set-output name=publish::false"
          fi
        fi
