name: 'Home Assistant helper: release-assets'
description: 'GitHub action helper: release-assets'
inputs:
  github_token:
    description: GITHUB_TOKEN with 'contents' write permission
    required: true
  paths:
    description: Comma-separated list of files and / or folders
    required: true
  file_map:
    description: |
      Filter and map file names to content types. E.g.
      "*.whl=application/zip, *.tar.gz=application/gzip"
    required: true
  delete_existing_assets:
    description: Delete existing assets before upload
    required: false
    default: true
    type: boolean

runs:
  using: composite
  steps:
    - name: Fail if not release event
      if: github.event_name != 'release'
      shell: bash
      run: |
        echo "::error::Action can only be run for 'release' events"
        echo "::error::Current event_name: '${{ github.event_name }}'"
        exit 1
    - name: Run upload script
      shell: bash
      run: |
        echo "::group::Upload assets"
        CONTEXT=$(echo '${{ toJSON( github.event.release ) }}' | jq -c 'del(.author)')

        python3 ${{ github.action_path }}/upload_assets.py \
          --token "${{ inputs.github_token }}" \
          --release_ctx "$CONTEXT" \
          --file_map "${{ inputs.file_map }}" \
          --delete_existing_assets "${{ inputs.delete_existing_assets }}" \
          --paths "${{ inputs.paths }}"
        echo "::endgroup::"
