name: 'Home Assistant helper: info'
description: 'GitHub action helper: info'
inputs:
  path:
    description: The relative dir path to where the type files are
    required: false
    default: '.'
outputs:
  architectures:
    description: Returns the supported architectures
    value: ${{ steps.architectures.outputs.architectures }}
runs:
  using: "composite"
  steps: 
    - shell: bash
      id: architectures
      run: |
        archs=[]
        mkdir -p "${{ github.action_path }}/bin"
        wget -q -O "${{ github.action_path }}/bin/yq" https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        chmod a+x "${{ github.action_path }}/bin/yq"
        echo "${{ github.action_path }}/bin" >> "$GITHUB_PATH"

        for file_type in json yml yaml; do
          if [[ -f "${{ inputs.path }}/build.${file_type}" ]]; then
            archs=$(yq e -N -M '.build_from | keys' -o=json -I=0 "${{ inputs.path }}/build.${file_type}")
            break
          elif [[ -f "${{ inputs.path }}/config.${file_type}" ]]; then
            archs=$(yq e -N -M '.arch' -o=json -I=0 "${{ inputs.path }}/config.${file_type}")
            break
          fi
        done

        echo "::set-output name=architectures::$archs"
