name: Test hassfest

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  hassfest:
    runs-on: ubuntu-latest
    name: hassfest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      
      - name: Test hassfest
        uses: ./hassfest
