name: Test hassfest

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  jq:
    runs-on: ubuntu-latest
    name: jq
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Test hassfest
        uses: ./hassfest